name: Clean Preview

on:
  pull_request:
    types: [closed]

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: gh-pages

    - name: Delete PR preview
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git rm -rf pr-${{ github.event.pull_request.number }}
        git commit -m "Delete preview for PR #${{ github.event.pull_request.number }}"
        git push